name: "Team Peggle"
subtitle: "Straight up Pegglin"

markdown: redcarpet

markdown_ext:  markdown,md

contact:
    steam: "http://steamcommunity.com/groups/TEAMPEGGLE"
    email: "badmin@teampeggle.com"
